version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - app/.env
    command: ["./wait-for-mongo.sh"]
    volumes:
      - ./wait-for-mongo.sh:/wait-for-mongo.sh
    working_dir: /app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
